# Global metadata
baseUrl: "https://hugo-test.eddie-summers.com/"
languageCode: "en-uk"
title: "Eddie Summers"

# Sidebar navigation
Menus:
  main:
    - Name: "GitHub"
      URL: "https://github.com/esummers1"
    - Name: "LinkedIn"
      URL: "https://www.linkedin.com/in/eddiesummers"

# Hyde theme settings
theme: "hyde"
params:
  description: "Thoughts on programming, fitness and other things."
  themeColor: "theme-custom"

# Markup configuration
markup:

  # Code highlighting
  highlight:
    codeFences: true
    style: dracula
