# Global metadata
baseUrl: "https://eddie-summers.com/"
languageCode: "en-uk"
title: "Eddie Summers"
theme: "vulcan"
googleAnalytics: "UA-59854355-2"

# Hyde theme site params
params:
  description: "Thoughts on programming, fitness, and other things."
  socialLinks:
    linkedIn: "https://www.linkedin.com/in/eddiesummers"
    gitHub: "https://github.com/esummers1"

# Taxonomies
# (tags & categories are default, but must be present if you want custom ones)
taxonomies:
  tag: "tags"
  category: "categories"

# Markup configuration
markup:

  # Code highlighting
  highlight:
    codeFences: true
    style: dracula
