name: Integration

on:
  push:
    branches-ignore:
      - master

jobs:
  build:
    name: Integration
    runs-on: ubuntu-latest

    steps:
      - name: Check out source
        uses: actions/checkout@v2

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2.4.13

      - name: Build with Hugo
        run: hugo
